config/routes.rb
Rails.application.routes.draw do
  root "frontend#index"
  
  resources :products do
    resources :properties, only: [:edit, :update, :create, :destroy]
  end
  resources :category 
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category, optional: true
    has_many :properties, dependent: :destroy

    has_one_attached :image

    validates :sku , presence: true, length: {is: 12}
    validates :title , presence: true
    validates :price , numericality: true
    validates :image , presence: true
    validates :cateID, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
   belongs_to :product, foreign_key: true, optional: true
   
   has_one_attached :image
   
   validates :title, presence: true
   validates :image , presence: true
   validates :quantity , presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    attr_reader :password

    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :password, confirmation: true, length: {minimum:6}
    validates :phone, length: {is: 9}
    validates :date_born, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController

    def index
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_category, only: %i[ show edit update destroy create new]

  # GET /products or /products.json
  def index
    @categories = Category.where('status', true)
    @q = Product.ransack(params[:q], cateID_eq: @categories)
    @products = @q.result.paginate(page: params[:page], per_page: 4).order('created_at DESC')
  end
  
  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_category
      @category = Category.where('status', true)
    end
    
    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:sku, :cateID, :title, :price, :image)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    before_action :set_property, only: %i[edit create destroy]
    before_action :set_find_property, only: %i[edit update destroy]

    def create
        @property = @product.properties.create(property_params)
        @product.quantity = Property.where("product_id = #{params[:product_id]}").sum(:quantity)
        respond_to do |format|
            if @product.save
                format.html { redirect_to @product, notice: "Property was successfully created." }
                format.json { render :show, status: :created, location: @property }
            else
                format.html { render 'products/show', status: :unprocessable_entity }
                format.json { render json: @property.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit 
    end

    def update
        respond_to do |format|
            if @property.update(property_params)
              format.html { redirect_to @product, notice: "Product was successfully updated." }
              format.json { render :show, status: :ok, location: @property }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @property.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def destroy
        @property.destroy
        @product.quantity = Property.where("product_id = #{params[:product_id]}").sum(:quantity)
        if @product.save
            redirect_to product_path(@product)
        end
    end

    private
    def set_property
        @product = Product.find(params[:product_id])
    end

    def set_find_property
        @property = @product.properties.find(params[:id])
    end

    def property_params
        params.require(:property).permit(:title, :quantity, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(users_param)
        if @user.save
          redirect_to products_path, notice: "Register successfully."
        else
          render :new
        end
    end
    
    private
    def users_param
        params.require(:user).permit(:email, :password, :password_confirmation, :date_born, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/front_end_helper.rb
module FrontEndHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/category/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <%= link_to 'Back', products_path, class:'btn btn-danger mb-3' %>
    <div class="card">
    <h5 class="card-header">Category list</h5>
        <div class="card-body">
            <table class="table table-hover table-bordered" >
                <thead>
                    <tr>
                        <th>Category's name</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <% @categories.each do |category|%>
                        <tr>
                            <td><%=category.title%></td>
                            <td><%=category.status == true ? :'Shown':'hiden' %></td>
                        </tr>
                    <% end %>
                </tbody>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manage Product</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h4>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :sku %>
    <%= form.text_field :sku , class:'form-control w-25'%>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title , class:'form-control w-25'%>
  </div>

  <div class="form-group">
    <%= form.label :Category %>
    <%= form.select :cateID, @category.map{ |c| [c.title, c.id]} %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price , class:'form-control w-25'%>
  </div>

  <div class="form-group">
    <%= form.label :Image %>
    <%= form.file_field :image , class:'form-control w-25'%>
      <% if product.image.attached? %>
        <div class='image-product my-2'> 
            <%= image_tag(product.image, style: 'width:100%')%>
        </div> 
      <% end %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class='container'> 
    <%= link_to 'Back', products_path %> | 
    <%= link_to 'Show', @product%>
    <h4>Editing Product</h4>
    <%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<div class="container">
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>
  <div class="card">
  <h5 class="card-header">Product list
  <%= link_to "Register", new_user_path, class:'btn btn-dark float-end' %></h5>
    <div class="card-body">
        <div class='mb-4'>
          <%= link_to 'New Product', new_product_path, class:'btn btn-success float-end' %>
          <%= link_to 'Category list', category_index_url, class:'btn btn-warning float-end me-2' %>
          <%= search_form_for @q do |f| %>
            <%= f.label :title_cont %>
            <%= f.select :cateID_eq, options_for_select([['default',nil]]+ @categories.map{|c| [c.title, c.id]})%>  
            <%= f.search_field :title_cont %>
            <%= f.submit%>
          <% end %>
        </div>
        <table class="table table-hover table-bordered" >
          <thead>
            <tr>
              <th class='text-center'>Category</th>
              <th class='text-center'>Sku</th>
              <th class='text-center'>Title</th>
              <th class='text-center'>Price</th>
              <th class='text-center'>Quantity</th>
              <th class='text-center'>Image</th>
              <th class='text-center' colspan="3">Choose</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td class='text-center'><%= product.cateID %></td>
                <td class='text-center'><%= product.sku %></td>
                <td ><%= product.title %></td>
                <td class='text-center'><%= product.price %></td>
                <td class='text-center'><%= product.quantity %></td>
                <td class='text-center'>
                  <div class='image-product'>
                    <%= image_tag(product.image, style: 'width:100%')%>
                  </div>
                </td>
                <td class='text-center'><%= link_to 'Show', product , class: 'btn btn-info'%></td>
                <td class='text-center'><%= link_to 'Destroy', product, class: 'btn btn-danger',method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class='mx-auto'>
      <div class="digg_pagination">
        <%= will_paginate @products  %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class='container'> 
    <%= link_to 'Back', products_path %>
    <h4>New Product</h4>
    <%= render 'form', product: @product %>
</div>

app/views/products/show.html.erb
<div class="container py-2">
  <%= link_to 'Back', products_path, :class => 'btn btn-danger mb-2' %>
  <p id="notice" class='text-success'><%= notice %></p>
  <div class="card">
    <h5 class="card-header"><%= @product.title %>
    <%= link_to 'Edit', edit_product_path(@product), :class => 'btn btn-warning' %>
    </h5>
    <div class="card-body">
      <div class='row align-items-start'>
          <div class='col'>
          <p class="lead">
            <strong>Sku:</strong>
            <%= @product.sku %>
          </p>

           <p class="lead">
            <strong>Category:</strong>
            <%= @product.cateID %>
          </p>

          <p class="lead"> 
            <strong>Price:</strong>
            <%= @product.price %>
          </p>

          <p class="lead">
            <strong>Quantity:</strong>
            <%= @product.quantity %>
          </p>
          <% if @product.property_ids.any? %>
            <p lass="lead">Properties</p>
            <table class="table table-hover table-bordered" >
              <thead>
                  <tr>
                      <td>Title</td>
                      <td>Quantity</td>
                      <td>Image</td>
                      <td>Delete</td>
                  </tr>
              </thead>
              <tbody>
                <%= render @product.properties %>
              </tbody>
            </table>
          <% else %>
            <p>Product haven't any properties</p>
          <% end %>
          <p class="lead">
            <strong>Image:</strong>
              <div class='image-product'>
                <%= image_tag(@product.image, style: 'width:100%')%>
              </div>
          </p> 
          </div>
          <div class='col'>
            <div class='card w-50 float-end'>
            <h4 class="card-header">Add properties</h4>
              <div class='card-body'>
                <%= render 'properties/form' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<%= form_with model: [@product, @product.properties.build] do |form| %>
    <div class="form-group">
        <%= form.label :Title %><br>
        <%= form.text_field :title, class:'form-control'%>
    </div>
    <div class="form-group">
        <%= form.label :Quantity %><br>
        <%= form.text_field :quantity, class:'form-control'%>
    </div>
    <div class="form-group">
        <%= form.label :Image %>
        <%= form.file_field :image , class:'form-control'%>
        <% if @product.properties.build.image.attached? %>
            <div class='image-product my-2'> 
                <%= image_tag(@product.properties.build.image, style: 'width:100%')%>
            </div> 
      <% end %>
    </div>
    <div class='mt-2'>
        <%= form.submit %>
    </div>
<% end %>

app/views/properties/_property.html.erb
<tr>
    <td><%=property.title%></td>
    <td><%=property.quantity%></td>
    <% if property.image.attached? %>
        <td>
            <div class='image-property'>
                <%= image_tag(property.image, style: 'width:100%')%>
            </div>
        </td>
    <%end%>
    <td><%= link_to 'Destroy',product_property_path(property.product_id, property.id), class: 'btn btn-danger',method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/users/index.html.erb
<div class="container">
  
</div>

app/views/users/new.html.erb
<div class="container">
<h1>Register
<%= link_to "Back", products_path, class: 'btn btn-danger' %>
</h1>
<div class="card">
  <div class="card-body">
      <%= form_with model: @user do |form| %>
        <div class="form-group">
          <%= form.label :'Email' %>
          <%= form.text_field :email , autofocus: true, class: "form-control", placeholder: 'Input email..', autocomplete: "email"%>
          <% @user.errors.full_messages_for(:email).each do |message| %>
            <div class='text-danger'><%= message %></div>
          <% end %>
        </div>
        <div class="form-group">
          <%= form.label :'Password' %>
          <%= form.password_field :password , class: "form-control", placeholder: 'Input password..', autocomplete: "new-password"%>
            <% @user.errors.full_messages_for(:password).each do |message| %>
                <div class='text-danger'><%= message %></div>
            <% end %>
        </div>
        <div class="form-group">
          <%= form.label :'Confirm password' %>
          <%= form.password_field :password_confirmation , class: "form-control", placeholder: 'Input confirm password..', autocomplete: "new-password" %>
            <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
                <div class='text-danger'><%= message %></div>
            <% end %>
        </div>
      
        <div class="form-group">
          <%= form.label :'Date born' %>
          <%= form.text_field :date_born , class: "form-control", placeholder: 'Input date..', type: :date%>
            <% @user.errors.full_messages_for(:date_born).each do |message| %>
                <div class='text-danger'><%= message %></div>
            <% end %>
        </div>
       
        <div class="form-group">
          <%= form.label :'Phone' %>
          <%= form.text_field :phone , class: "form-control", placeholder: 'Input number phone..'%>
            <% @user.errors.full_messages_for(:phone).each do |message| %>
                <div class='text-danger'><%= message %></div>
            <% end %>
        </div>
        <div>
          <%= form.submit:'Register' , class: 'btn btn-primary'%>
        </div>
      <% end %>
  </div>
</div>
</div>